baseURL = 'http://localhost/'
languageCode = 'en-us'
title = 'Philippe Saade'
theme = 'papermod'


[params.homeInfoParams]
Title = "Hi there 👋"
Content = "I build AI apps and share guides"

[[params.social]]
linkedin = "https://www.linkedin.com/in/philippe-saad%C3%A9-26972b149/"
github = "https://github.com/PhilSad"
